mode: virtual
base_url: "https://openapivts.koreainvestment.com:29443"

app_key: "PSxpyGbqG2LKeVlFNxkCIZEFHLu2w24wce4A"
app_secret: "F8ujHmSUxpV5xbG18mmZ/OiJ5a4MJciJ6IA1I74ZUcgAueXVSMiwmUZUaEbdb6Nfotl46lF7fqkjUdif2TV9GbfZt7tVHwukpcpaeO28jR5G+t00yUdMw+8+dsfB8O609mGpG+Y7b4GsvLs/OmsQtVFoNXz+2l0rtflj4LtJ6ZDS6T0UhCY="

cano: "50194135"
acnt_prdt_cd: "01"

stock_code: "005930"
stock_name: "삼성전자"

# 한 번 매수할 금액
buy_amount: 1000000
interval_sec: 5

# 루프 간격 초
interval_sec: 5

simulation_mode: true